### PR TITLE
bugfix for setup_lak

### PR DESCRIPTION
**Pull request by mnfienen**
Needed to accomodate the case where no stage/vol/area tables are passed in the YML configuration file. Just set a flag to None if no tables block.

### CODE REVIEW

**Comment by mnfienen** [comment]
this build fail seems to be related to the default of not including horizontal connections for lakes:

`assert not info.loc[info.claktype == 'horizontal', 'cellface'].isnull().any()`

**Comment by mnfienen** [comment]
looks like that assert is just verifying that the connections file was written. Can use "vertical" rather than "horizontal" and all should be fine

**Review by aleaf — CHANGES_REQUESTED** [review]
hey @mnfienen this looks good but can you modify so that it's just the changes to mf6model.py? I ended up turning the horizontal connections back on for the pleasant_mf6 test so that they continue to get tested.

**Comment by mnfienen** [comment]
yeah - I always struggle with my forkss going of the rails like this. I think I'll just make a new fork

**Comment by aleaf** [comment]
You should be able to fix the commits by rebasing to the upstream (and then pushing that to your fork). But those aren't as important because they can be rebased on merging the pull request. For the other 2 files besides mf6model.py I think resetting them to the last commit on the upstream would work. I'd make the change myself but I think the only way to "cherry pick" pull requests is to pull the branch down to your machine and do it manually.

**Comment by mnfienen** [comment]
no worries - for now just going to go nuclear and make a new fork. the only current relevant changes are on mf6model.py anyway

**Pull request closed without merging**
